ccmbioinfo/crg2

config.yaml
rules/calling.smk
rules/mapping.smk
wrappers/samtools/remove_decoys/environment.yaml
wrappers/samtools/remove_decoys/meta.yaml
wrappers/samtools/remove_decoys/wrapper.py

* Using wrapper instead of shell script to maintain samtools versioning (per environment.yaml)
* Comparison of bans from variantbam vs samtools removal of decoy reads. Identical file size:
```
-rw-r--r-- 1 delvinso 8867732622 May 27 14:46 NA12878-1.no_decoy_reads.bam
-rw-r--r-- 1 delvinso 8867732622 May 28 16:54 NA12878-1.no_decoy_reads_st.bam
```
* Dry run passes
```
rule remove_decoy:
input: recal/NA12878-1.bam, /home/delvinso/cre/data/grch37d5.decoy.bed
output: decoy_rm/NA12878-1.removed_reads.bam, decoy_rm/NA12878-1.no_decoy_reads.bam
log: logs/remove_decoys/NA12878-1.log
jobid: 270
wildcards: sample=NA12878, unit=1
threads: 8
resources: mem_mb=10000
Job counts:
count	jobs
1	all
86	call_variants
86	combine_calls
86	genotype_variants
2	hard_filter_calls
1	map_reads
1	merge_calls
1 …
```

add remove decoy rule, config and associated wrappers

---

README.md
config.yaml
envs/cre.yaml
rules/annotation.smk
rules/common.smk
rules/snvreport.smk
schemas/config.schema.yaml

- Panel and panel+flank snv report generation is optional and automatically generated
- config.yaml is a bit cleaner. Project specific values are now placed under the dictionary called "run"
- Annotation files have been copied over to the Common directory. Updated file paths to point to these files
- Added a SNV PASS rule before the vcf -> gemini.db conversion

Panel, Panel+Flank SNV reports, cleaned up config.yaml, updates to file paths, README updates,

---

config.yaml
rules/common.smk
rules/mapping.smk
schemas/units.schema.yaml
units.tsv
wrappers/bedtools/bamtofastq/environment.yaml
wrappers/bedtools/bamtofastq/wrapper.py

This adds the ability to use a bam file as input to crg2. Fastqs will be extracted from the bam file using bedtools bamtofastq and then re-aligned to the reference specified in the config. I added a 'bam' field into the units.tsv field. I also added a bam field under "run" in the config file: the default is False, but if set to True, the pipeline will use the bam file specified in the units.tsv file as input. 
I tried to set the units.schema.yaml to require fq1 or bam but couldn't figure it out :/
See `/hpf/largeprojects/ccmbio/mcouse/testing/crg2/NA12878_test_from_bam/` for example units.tsv and config.yaml files.

bamtofastq functionality for bam input (CRG2-7)

---

Snakefile
config.yaml
dnaseq.pbs
envs/crg.yaml
envs/samtools.yaml
envs/svscore.yaml
rules/annotation.smk
rules/common.smk
rules/mapping.smk
rules/qc.smk
rules/snvreport.smk
rules/sv.smk
rules/svreport.smk
wrappers/bcftools/view/wrapper.py
wrappers/snpeff/wrapper.py

My last commit!
- Bumped up Qualimap ram. 4GB is too low. Online sources suggest that we use the whole size of the bam, as to prevent garbage collection as much as possible
- Implemented annotations for SVScore. Because this tool cannot be found on Anaconda.org, it must be run under the shell directive. I added an environment file as well.
- Implemented SV report generation. Has it's own isolated environment.
- Added an isolated environment for samtools. Previously it was using the default conda installation. Not really an issue, but might as well keep it's environment separate. Also added a temp() for the decoy removed bam file since we keep the bam produced from recal rule.
- Added a PIPELINE_VERSION in Snakefile. This value should be updated along with each git release. This value is …

SV report generation

---

vcfanno/crg.vcfanno.conf

the following changes must also be made in cre:
`cre.gemini2txt.vcf2db.sh`
- add ` spliceai_score as spliceai_score,\`  to `sQuery`
`cre.vcf2db.R`
- add `'spliceai_score'` so it is selected in these functions:
- `select_and_write2()` (line 367 or so) 
- `clinical_report()` (line 757 or so)

add spliceai indel and snv annotations to crg2

---

parser.py
rules/common.smk
rules/mapping.smk
rules/qc.smk
scripts/fastq_prep.py

- I added a rule to concatenate fastqs in the event that there are multiple fastqs per read. The script associated with this rule is based on https://github.com/ccmbioinfo/crg/blob/master/crg_wrapper.py, which @aarthi-mohan wrote for crg
- I also standardized read file naming to the conventional 'R1' and 'R2' notation, because this seems to be almost exclusively the format in which we receive fastqs. 
- I will need to rename the test files (/hpf/largeprojects/ccm_dccforge/dccdipg/Common/NA12878/NA12878.bam_1.fq, /hpf/largeprojects/ccm_dccforge/dccdipg/Common/NA12878/NA12878.bam_2.fq) that are linked in the units.tsv file, but am waiting for write permissions for the directory. 
closes #17

Add rule to concatenate fastqs

---

config.yaml
wrappers/vep/environment.yaml

Environment for vep v104 is now installed on the hpf (/hpf/largeprojects/ccm_dccforge/dccdipg/Common/snakemake/6f4af8a1/share/ensembl-vep-104.0-0/)

Upgrade vep to v104

---

rules/mapping.smk

bedtools bamtofastq does not actually gzip the fastqs, and fastqc_screen will fail if bams are not gzipped. I added a rule to gzip the fastqs.  Closes #48.

gzip fastqs after bamtofastq

---

rules/mapping.smk
wrappers/bedtools/bamtofastq/wrapper.py

When the input was fastq, snakemake would execute bamtofastq, resulting in errors. Incorporating the gzip fastq step into bamtofastq  seems to avoid that issue.

fix bug fastq_prep vs bamtofastq issue

---

README.md
Snakefile
config.yaml
envs/hpo_to_panel.yaml
rules/snvreport.smk
scripts/clean_gtf.py
scripts/hpo_to_panel.py

This PR adds:
- A script for generating gene coordinates for Ensembl and RefSeq genes (clean_gtf.py, credit to @delvinso who made the original script for STAGER, https://github.com/ccmbioinfo/sampletracker2stager/blob/master/variants/clean_gtf.py)
- A script to generating a bed file corresponding to the genes listed in the HPO files we receive from CHEO (from Phenome Central or G4RD), hpo_to_panel.py. This script queries the genes listed in the HPO file against both the Ensembl and RefSeq gene files to extract coordinates (most genes have Ensembl gene IDs, but not all). It also looks for gene aliases in the HGNC file and then re-queries the RefSeq gene file for genes that are not mapped in the initial step.
- conditional rules for generating the bed file and panel reports if HPO terms are …

HPO to panel bed

---

parser.py

If HPO text file for a family exists in ~/gene_data/HPO, the parser will add this file to the config.yaml. Must be in the format <family>_HPO.txt.
Similarly, if a ped file for a family exists in ~/gene_data/pedigrees, the parser will add this file to the config.yaml. Must be in the format <family>*ped

link hpo and ped files if they exist

---

README.md
config.yaml
rules/mapping.smk
units.tsv

Previous fix for usage of fastq_prep or bamtofastq rules depending on files specified in units.tsv did not work! The fix in this PR requires that the input type (fastq or bam) be specified in config.yaml. Unfortunately, this means that we cannot support a mix of bams and fastqs at the moment. I tried a few things to dynamically select the rule, but because the input is the same file for both rules (units.tsv), rather than the actual fastq or bam input files, this doesn't seem to work. Will have to return to this in the future. I also updated the README so that it is up to date with recent changes to the pipeline.

temp fix for bamtofastq rule priority issue

---

README.md
rules/snvreport.smk
scripts/add_hpo_terms_to_wes.py

Once the CSV reports in `report/coding` `report/panel` `report/panel-flank` is available, run the following or edit the `dnaseq_cluster.pbs` file with the target. Annotated reports are stored in `report/hpo_annotated`
`snakemake --use-conda -s $SF --conda-prefix $CP --profile ${PBS} -p report/hpo_annotated`
1.  Properly names  reports inside `report/panel` and `report/panel-flank` with symlink
2. Copied  `add_hpo_terms_to_wes.py` from ~/cre/ -> ~/crg2/scripts and added 3rd argument to pass <output> directory

HPO annotation

---

rules/mapping.smk
wrappers/bedtools/bamtofastq/wrapper.py

Fixed the file naming issue in the bamtofastq step that prevented the fastq files from being compressed (which caused downstream issues with the fastqc and fastq screen steps).

Bamtofastq bug

---

wrappers/bedtools/bamtofastq/wrapper.py

bamtofastq_cmd for sorted BAMs likely was failing all along, due to a missing semi-colon, and improper indentation of the fq_gzip_cmds. Fixed both of these, wrapper now works for both sorted and unsorted BAMs.

syntax/format changes to fix application to sorted BAMs

---

config.yaml
rules/mapping.smk
wrappers/picard/markduplicates/wrapper.py

Ran into error in MarkDuplicates step:
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
These changes set Java heap space to 2g for the MarkDuplicates step

Increase Java mem to 2g for MarkDuplicates

---

rules/common.smk

Previously, python threw an error if the participant codename was an integer (e.g. 120401). This fix converts the participant codename to a string so that the str.replace() function does not throw an error.

Allows participant codenames to be integers when creating ped

---

vcfanno/cre.vcfanno.conf
vcfanno/crg.vcfanno.conf

Downloaded full genome CADD files from [https://cadd.gs.washington.edu/download], specifically **All possible SNVs of GRCh37/hg19** and **48M InDels to initiate a local setup**.
- Removed current CADD annotation from the dbNSFP block in the vcfanno config.
- Added in new CADD annotation blocks to the vcfanno config from the full genome SNV and indel tsv files.

Adding genome-wide CADD scores.

---

config.yaml
rules/annotation.smk
rules/cre/annotation.smk
schemas/config.schema.yaml
wrappers/vep/wrapper.py

Removed maxentscan and human_ancestor_fasta (related to the LOFTEE VEP plugin) from the VEP requirements in the pipeline, as we no longer use either of these tools. Edits made to the:
- VEP rule in both the crg and cre annotations.smk
- VEP wrapper script
- Config schema file 
- Config.yaml template
A [corresponding change](https://github.com/ccmbioinfo/cre/pull/39) will also be made to the cre.vep.sh script in the cre repository, so that this change can also be applied when running the generate_reports.sh script from that repo.

VEP config changes

---

README.md
config.yaml
rules/mapping.smk
schemas/config.schema.yaml
schemas/units.schema.yaml
units.tsv
wrappers/samtools/fastq/environment.yaml
wrappers/samtools/fastq/wrapper.py

Added a cramtofastq rule + wrapper, using samtools fastq, based on [this script](https://github.com/ccmbioinfo/cre/blob/master/cram2fastq_samtools.pbs). Also made changes to the config and schema so that it is possible to change the paths to both the old and new references in the config.yaml. 
So overall usage of this rule: 
(1) Put path to cram file in the units.tsv.
(2) Set input in config.yaml to "cram".
(3) Change the old/new cram references in the config.yaml, or use the default ones.
Note: The samtools fastq step produces temporary bam files in the central project directory while it runs, making it look a bit clunky. These are removed at the end of the step, so not sure if this is a big concern that we need to address.

Cramtofastq rule

---

config.yaml

Add --DisableSanityCheck flag to verifybamID2 command so that verifybamID2 doesn't fail if there are fewer than 10,000 SNP markers. This is relevant for exomes, which sometimes fall just short of 10K markers. 
https://groups.google.com/g/verifybamid/c/KtnfvkeauXk?pli=1

add --DisableSanityCheck to verifybamID2

---

parser_exomes.py

Some fastq-input exomes fail at the BWA mapping step because of a "paired reads have different names" bwa-mem error. This is because the R1 and R2 fastq files get concatenated in different orders. I have added a sorted() function to the parser script to order the fastq files in the directory first and prevent this from happening.

Exome parser fix for fastq-input exomes

---

parser_exomes.py

The current exome parser will only recognize fastq.gz files that are named *_R1_*.fastq.gz and *_R2_*.fastq.gz. Some files are instead named *_1_*.fastq.gz and *_2_*.fastq.gz. I have added an extra glob command so that these will be recognized. I also tried simply making the glob more flexible, like this ->  *_*1_*.fastq.gz, so that one glob works for both formats, but this runs into an issue with files that have IDs in the filename ending in 1 or 2. I tested the parser out with 2 exomes, one with each format, it works fine. 
Also changed the wording of the read number error: the old wording made me think that the number of the actual reads in the fastq did not match, when really it is just trying to say that the number of R1 files does not match the number of R2 files.

Exome parser fix

---

rules/multiqc_config.yaml
rules/qc.smk
scripts/callerwise_annotation.sh

A few exomes had errors in annot_caller step due to unsorted positions. Testing of the fix in callerwise_annotation.sh was successful

add sorting step to script

---

Snakefile
config.yaml

These changes will allow crg2 to begin the pipeline from the VCF annotation step, which is useful when we have an external VCF that we'd like to annotate with the in-house annotations, and produce reports.

Accept VCFs as input for annotation

---

rules/cre/snvreport.smk
rules/snvreport.smk

cre/cre.sh calls ~/cre/vcf.ensemble.getCALLERS.sh, which requires a path to a reference fasta

Specify path to reference fasta when calling cre/cre.sh

---

config.yaml

- Changed the compression level to 5 for the BQSR step in config.yaml file.
- Performed benchmarking using NA12878 dataset and validation and report comparison on exome 428
Closes #137

Modified BQSR compression level to 5

---

parser_exomes.py

Incorporates regex to differentiate between R1 and R2 reads, and account for reads where identifiers lack R prefix (_1_ and _2_, e.g. 670513-P_HVWLCBCXX-2-ID01_1_sequence.fastq.gz).

Add fastq regex

---

utils/check_dup_rate.sh

Modified the check_dup_script.sh file to print sample names along with duplication rates for all samples in the family.

Check dup script prints sample name + dup rate for all samples

---

config.yaml
envs/ehdn.yaml
rules/str.smk

Provides paths to EHDN 0.70 executable, EHDN jsons called on 1000G samples, and reference fasta as arguments to crg/crg.ehdn.sh.

Remove hpf hardcoded values for ehdn

---

Snakefile
config.yaml
envs/coverage.yaml
pbs_profile/pbs_config.yaml
rules/common.smk
rules/cre/snvreport.smk
rules/qc.smk
utils/bam.coverage.base_wise.stat.py
utils/bam.coverage.less20.sh
utils/bam.coverage.per_exon.sh
wrappers/multiqc/wrapper.py
wrappers/peddy/wrapper.py
wrappers/picard/markduplicates/wrapper.py

This PR adds the following:
- A rule to generate bam files with duplicates removed: rules/qc/remove_duplicates
- A rule to generate coverage reports from bams with duplicates removed: rules/qc/calculate_coverage
- A rule to copy the report to MinIO: rules/cre/snvreport/minio
- An input function to check whether only variant reports should be copied to MinIO, or variant reports, coverage reports, and multiqc report: rules/cre/snvreport/check_qual
- A checkpoint that is evaluated by check_qual so that Snakemake knows whether or not to generate coverage reports
- A parameter config["run"]["minio"]  that specifies base path to MinIO directory. If empty, reports won't be copied anywhere.
Tested on family 2086 (dup percentage >20% in at least one sample) with MinIO path arbitrarily set to …

Automate coverage report generation for exomes 

---

config.yaml

config["annotation"]["ehdn"]["files"] had the CHEO-RI path, not the hpf path. This led to the str/EHDN/<family>_manifest.txt file lacking the 1000G samples, which disrupted outlier detection downstream.

Fix EHDN files path

---

parser_genomes.py

Changes will allow units.tsv and samples.tsv to be written to the project directory even if a pedigree is not specified, or does not validate. The job will not be submitted, but can be manually submitted if the user decides a pedigree is not necessary; no de novo report will be produced.

Write units and samples tsv even if ped does not validate

---

config.yaml

This directory was accidentally deleted following the deletion of the dccforge/results cleanup. We have retrieved the C4R exome counts and HGMD databases from the CHEO-RI space, and copied them to the central crg2 annotations directory. Submitting this PR to change the cre database path prefix to that directory.

changed cre deleted database path to central annotations directory

---

config_cheo_ri.yaml
config_hpf.yaml
rules/mapping.smk
wrappers/samtools/fastq/wrapper.py

Rather than resorting to the @SQ UR field in the CRAM header, use REF_CACHE/REF_PATH. Samtools first looks to the REF_CACHE, then EBI, than the UR field (https://www.htslib.org/workflow/cram.html). Using a REF_CACHE should avoid samtools attempting to query EBI and hanging.

Use samtools REF_CACHE to decompress CRAM

---

rules/snvreport.smk

If a pedigree is provided in the config so that a de novo report is produced, annotate this with HPO terms for GenomeRounds.

Annotate de novo report with hpo terms for GenomeRounds

---

rules/qc.smk
wrappers/samtools/markdup/environment.yaml
wrappers/samtools/markdup/wrapper.py

The most recent version of Picard available via Conda doesn't seem to support CRAM files, so I used samtools markdup to remove duplicates from the input cram.

Remove duplicates from cram instead of bam

---

wrappers/snpeff/wrapper.py

[snpeff will not annotate \<INS\>](https://github.com/pcingola/SnpEff/issues/344), so replace \<INS\> with N so that we at least get the gene(s) that the insertion falls into. Without this fix, the insertions aren't annotated against any gene, and so in the report appear to be intergenic.

Replace symbolic INS with N

---

scripts/MELT_report.py

END is always the same as POS for insertions, so this column can be removed. Likewise, SVTYPE is always INS so can be removed.

remove END and SVTYPE cols

---

config_hpf.yaml
rules/mapping.smk
wrappers/samtools/fastq/fastq_prep.py
wrappers/samtools/fastq/wrapper.py

The ora format is a reference-based compression format for FASTQ files. It is a lossless compression format, designed for very fast compression/decompression and high compression ratio. These files can be easily converted to bgzipped format using the [Dragen ORA Decompression Software](https://support-docs.illumina.com/SW/Decompression_v261/Content/SW/ORA/Decompression_Overview.htm) 
Installation directory: `/hpf/largeprojects/ccmbio/ajain/tools/orad_2_6_1`
Code modifications were done in fastq_prep.py file:
- Script first checks if the read extension is .gz or .ora
- If its .gz, then it concatenates the reads as usual
- If its .ora, it first decompresses the individual files, concatenates the reads and finally removes the .gz files from the main directory

added function to decompress .ora files

---

rules/cre/filtering.smk
slurm_profile/slurm-config.yaml

Issue: Annot_caller rule takes a very long time to complete
Fix:
- Increased time and memory for annot_caller rule in slurm_profile/slurm-config.yaml file
- Increased the number of jobs running in parallel from 15 to 50 in rules/cre/filtering.smk
Testing:
- Tested fix on 4 exomes for the Hiraki Lab which all ran to completion

Adjust resources for annot_caller rule

---

vcfanno/crg.vcfanno_hg38.conf

Adding FATHMM-XF scores into crg2 pipeline, where scores will be present within the INFO# field of the vcfs. Files containing scores relocated to /hpf/largeprojects/ccmbio/nhanafi/c4r/downloads/databases/GRCh38_FATHMM-XF_NC_edited.tsv.gz. Appropriate additions made to vcfanno config file, as presented below:

Adding FATHMM-XF into annotation pipeline with new branch: rvaran/FATHMM-XF

---

dnaseq_slurm_hpf.sh
vcfanno/crg.vcfanno_hg38.conf

Following the steps in https://github.com/orgs/ccmbioinfo/projects/5/views/1?pane=issue&itemId=54524505
I tested the pipeline with this change, and here is the output
```
Building DAG of jobs...
Checking status of 0 jobs.
Using shell: /usr/bin/bash
Provided cluster nodes: 4
Provided resources: cpus=64
Job counts:
count   jobs
25      combine_calls
25      gatk
25      genotype_variants
2       hard_filter_calls
1       input_prep
1       map_reads
1       mark_duplicates
1       merge_calls
1       merge_variants
1       mosdepth
1       pass
1       recalibrate_base_qualities
1       samtools_index
2       select_calls
1       vcfanno
1       vep
1       vt
91
Resources before job selection: {'cpus': 64, '_cores': 9223372036854775807, '_nodes': 4}
Ready jobs (1):
input_prep
Selected jobs …
```

 Incorporate LINSIGHT into annotation pipeline

---

utils/bam_slice_by_gene.py

Add compatibility for PacBio:
- Allows creation of BAM slices for both de novo assembled BAM and aligned BAM
- Hg38 coordinates
User must now specifiy the `--platform` argument (either PacBio or Illumina). 
I also removed the `path` argument. The script must be run in the directory containing the BAMs.

PacBio compatibility, remove -path argument

---

vcfanno/cre.vcfanno.conf
vcfanno/crg.vcfanno.conf

Add non-coding scores (nCER, ReMM, LINSIGHT) to WGS reports (panel, panel-flank, de novo). Scores are not added for exomes or WGS coding reports.

add ncER, ReMM, and LINSIGHT scores

---

wrappers/samtools/fastq/wrapper.py

Note: you will need to make sure the hpf account you're running the pipeline from has access to the iRods directory you've linked in units.tsv
Example iRods path: /resarchivezone/tcag/translational_genomics/illumina/genodermatoses/SZU25195/sample.cram

get cram from iRods archive

---

vcfanno/crg.vcfanno_hg38.conf
wrappers/vcf2db/wrapper.py

- Updated vcfanno config to point to gnomad v4 joint frequency annotation VCF
- Use this branch in conjunction with this cre branch [https://github.com/ccmbioinfo/cre/pull/63](https://github.com/ccmbioinfo/cre/pull/63)

gnomad V4 update for small variants

---

hg38/config_hpf.yaml
scripts/SVRecords/SVAnnotator.py
scripts/crg.intersect_sv_vcfs.py
scripts/process_gnomAD_v4_1_SV_bed.py

Update gnomAD SV annotations to v4.1 (from https://storage.googleapis.com/gcp-public-data--gnomad/release/4.1/genome_sv/gnomad.v4.1.sv.sites.bed.gz). Note: The BED file has duplicated END and SVTYPE columns, which I remove prior to annotation against sample SVs in line 504 of `scripts/process_gnomAD_v4_1_SV_bed.py`.

Update gnomAD SV annotations to v4.1

---

vcfanno/crg.vcfanno.conf

Add details of ClinVar conflicting status using the CLNSIGCONF field in the ClinVar VCF. For example, instead of just annotating a variant as `Conflicting_classifications_of_pathogenicity` it would be annotated as `Conflicting_classifications_of_pathogenicity;Uncertain_significance(2)|Likely_benign(3)`. Associated with [cre PR #64](https://github.com/ccmbioinfo/cre/pull/64).

Add ClinVar conflicting statuses

---

config_cheo_ri.yaml
config_hpf.yaml
wrappers/vep/environment.yaml
wrappers/vep/wrapper.py

Also downloaded the GRCh37 v113 annotation caches to the HPF (/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vep/homo_sapiens_merged/113_GRCh37) and CHEO-RI (/srv/shared/data/dccdipg/annotation/vep-cache/homo_sapiens_merged/113_GRCh37/) spaces. Removed the `--af_esp` from the VEP wrapper as it's no longer a valid parameter.

Update VEP to v113

---

vcfanno/cre.vcfanno.conf

- Update the cre.vcfanno.conf file to add clinvar conflicting status details for exome reports

Add clinvar conflicting status details for exome reports

---

Snakefile
config_cheo_ri.yaml
config_hpf.yaml
rules/str.smk
scripts/str/eh_sample_report.py

I compared the disease thresholds being used in our pipeline (derived from this [spreadsheet](https://docs.google.com/spreadsheets/d/1Z2ckjXid2yNqdPNYPCU8LadiQY4T8sxiE3KaiHrDcOk/edit?gid=0#gid=0)) to the pathogenic minima in [STRchive](https://strchive.org/) as listed in the hg19 BED file under the Resources tab. The Jupyter Notebook can be found at /hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation/ExpansionHunter/update_thresholds.ipynb.
Where the threshold differed between STRchive and our pipeline, I used the value reported by STRchive. The new reference file is at /hpf/largeprojects/ccm_dccforge/dccdipg/Common/annotation/ExpansionHunter/tandem_repeat_disease_loci_v1.1.2.tsv. I updated `scripts/str/eh_sample_report.py` to use the pathogenic minima rather than the custom text …

Update pathogenic disease thresholds in ExpansionHunter report 

---

rules/annotation.smk

**Bug description:** For genomes, there was a bug in the rule pass (rules/annotation.smk) because of which non-PASS variants were being retained in the VCF files.
**Fix:** Modified the params in rule pass.
**Testing:** Tested on one family (F396)
- No. of records in VCF (before bug-fix) = 4745987
- No. of records in VCF (after bug-fix) = 4702588

bug fix in rule pass

---

utils/README.md
utils/download_clinvar.sh

This script downloads hg19 and hg38 ClinVar VCFs, indices, and md5 files. It is compatible with both the hpf and G4RD/CHEO-RI servers. It also checks the md5sums of the downloaded VCFs.  Add `0 0 15 * * sh ~/crg2/utils/download_clinvar.sh` to your crontab (`crontab -e`) to update ClinVar on the 15th of every month.

Automate monthly ClinVar download 

---

vcfanno/crg.vcfanno.conf

- Scripts to generate the C4R genome TSV are located at /srv/shared/hpf/short_read_genomes/code/genome_db. 
- CHEO-RI TSV: /srv/shared/data/dccdipg/annotation/vcfanno/C4R_genomes_with_AC_samples_capped.tsv.gz.
- HPF TSV: /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/variation/C4R_genomes_with_AC_samples_capped.tsv.gz

Update C4R WGS counts
