README.md
config.yaml
envs/cre.yaml
rules/annotation.smk
rules/common.smk
rules/snvreport.smk
schemas/config.schema.yaml

Revert "Resolve dennis snv panel report conflict"

---

config.yaml
rules/qc.smk
wrappers/fastq_screen/wrapper.py
wrappers/qualimap/environment.yaml
wrappers/qualimap/meta.yaml
wrappers/qualimap/wrapper.py
wrappers/verifybamid2/environment.yaml
wrappers/verifybamid2/meta.yaml
wrappers/verifybamid2/wrapper.py

* logs for each tool added
* added params to config.yaml, should we have a separate section specifically for qc?
* as mentioned in slack, I still need to look into the naming consistency for samples in the final report.

adding MultiQC support for wrappers and rules for qualimap, verifybamid2, etc.

---

rules/mapping.smk

Sets initial bam file as temporary. (Issue #29)

---

wrappers/vt/environment.yaml

downgrade vt

---

pbs_profile/config.yaml

set notemp to false so temp() directives aren't ignored
closes #41

set notemp to false

---

vcfanno/crg.vcfanno.conf

combined ccmmarvin/crg/crg.vcfanno.conf &  gemini.conf

---

README.md
envs/crg.yaml

add annotsv documentation to readme

---

vcfanno/crg.vcfanno.conf

added config for UCE

---

rules/annotation.smk
rules/common.smk
rules/snvreport.smk
vcfanno/crg.vcfanno.conf

Generate de novo reports if pedigree file is present

De novo report

---

README.md
parser.py
sample_info.tsv

Parser bug fix

---

Snakefile
rules/mapping.smk

added a rule in mapping.smk and a line in rule_all

added a rule to generate md5sum for bam files

---

rules/common.smk
schemas/config.schema.yaml
schemas/samples.schema.yaml
schemas/units.schema.yaml

Generic project naming

---

envs/common.yaml
rules/annotation.smk
rules/calling.smk
rules/mapping.smk
rules/snvreport.smk

Wgs cleanup

---

envs/crg.yaml
rules/common.smk
rules/sv.smk
scripts/SVRecords/SVAnnotator.py
scripts/SVRecords/SVGrouper.py
scripts/SVRecords/__init__.py
scripts/crg.intersect_sv_vcfs.py
wrappers/manta/environment.yaml
wrappers/manta/wrapper.py

Generates a report from Manta BNDs.  Manta VCF is filtered by BNDs with at least one supporting split read, a depth of 10, and a mate depth of 10.

Manta BND report

---

config.yaml

Update GATK MQ filter to <30 for genomes

---

rules/common.smk
rules/qc.smk
wrappers/bcftools/stats/environment.yaml
wrappers/bcftools/stats/wrapper.py
wrappers/bcftools/view/wrapper.py
wrappers/peddy/environment.yaml
wrappers/peddy/wrapper.py

I created new wrapper for bcftools stats and added rules to generate bcftools statistics. This is tested to work well in exome 428 and genome 412.

incorporate bcftools statistics into multiqc report

---

pbs_profile/config.yaml
pbs_profile/config.yaml.save

changed --notemp flag to false

flag to delete temp files

---

utils/copy_reports_to_minio.sh

Added an extra line to allow the script to recognize and copy over the BND SV reports (that were part of the last release) to MinIO.

Upload BND report to MinIO

---

config.yaml
rules/snvreport.smk

Specify path to C4R and HGMD databases when calling cre.sh.

Add cre database path as argument

---

rules/cre/snvreport.smk
rules/snvreport.smk

Fix database path variable provided to cre.sh and also add to cre/snvreport.smk.

Fix database path

---

rules/cre/snvreport.smk
rules/snvreport.smk

Supply cre.sh full path to cre repo, so that cre does not have to be installed in home directory of user running the pipeline. Relevant to the Stager user running crg2.

Specify cre path

---

Snakefile
rules/mapping.smk
wrappers/samtools/view/meta.yaml
wrappers/samtools/view/wrapper.py

Convert recal/bam to recal/cram

Convert BAM to CRAM

---

README.md
exome_reanalysis.py
genome_reanalysis.py

Sets up directories and submits pipeline jobs to Slurm cluster on hpf based on requested WGS re-analyses specified in Stager CSV.

Genome re-analysis

---

Snakefile
config_hpf.yaml
envs/melt.yaml
rules/melt.smk
scripts/MELT_report.py
slurm-config.yaml
utils/wgs_gene_coverage/get_gene_coverage_py.sh
utils/wgs_gene_coverage/get_gene_exon_intron.py
wrappers/snpeff/wrapper.py

Note: To target MELT report generation, specify target rule (melt_report) in dnaseq_slurm_hpf.sh. Specifying target file will not work as the MELT target output is a folder and dates are included in the final report file name. See example of Snakemake command:
`snakemake --use-conda -s ${SF} --cores 4 --conda-prefix ${CP} --configfile ${CONFIG} --profile ${SLURM} -p melt_report`

add MELT to crg2

---

parser_genomes.py

Script now requires Stager analyses_report.csv as an argument (-a). The script will create a subfolder named after the analysis ID underneath the family ID, e.g. 700/10030, and the pipeline will be executed in this directory.

Include analysis id in output directory

---

vcfanno/crg.vcfanno_hg38.conf

added ncER annotation for non-coding variants to vcfanno

added ncER score annotation to vcfanno

---

vcfanno/crg.vcfanno_hg38.conf

add GreenDB annotation

---

hg38/config_hpf.yaml
rules/common.smk
rules/sv.smk
schemas/config.schema.yaml
scripts/crg.intersect_sv_vcfs.py

Removed the svscore rule and column annotations from the SV reports as the score is not particularly useful.

Remove svscore from pipeline

---

README.md
config_cheo_ri.yaml
envs/crg.yaml
envs/hpo_to_panel.yaml
rules/snvreport.smk
slurm_profile/config.yaml
wrappers/bedtools/intersect/environment.yaml
wrappers/manta/environment.yaml
wrappers/mity/call/environment.yaml
wrappers/mity/call/wrapper.py
wrappers/mity/normalise/environment.yaml
wrappers/mity/normalise/wrapper.py
wrappers/mity/report/environment.yaml
wrappers/mity/report/wrapper.py
wrappers/smoove/environment.yaml

Some features were not fully functional on the CHEO HPC4Health server. I had to define and recode some environments to get smoove and manta SV callers, panel reports, and mitochondrial reports working.

crg2-wgs for CHEO HPC4Health
